### PR TITLE
Added ZHA IKEA Rodret wireless dimmer

### PR DESCRIPTION
**Pull request by nwithan8**
## Blueprint Checklist

- [x] You viewed the README and conformed to the [naming conventions](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#title-naming-convention)
- [x] You ordered the actions as stated in the README [action order](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#order-convention)
- [x] All filenames are lowercase and uses '-' for spaces and **not** '_' while using {service-name}-{switch-name-or-type}.yaml format
- [x] Images are png
- [x] Image backgrounds are transparent and is cropped to the device boundries
- [x] Images has a maximum width of 800px and maximum height of 500px
- [x] There are no missing buttons or actions
- [x] Your integration/service is running on the latest version
- [x] You have tested your blueprints and made sure each button and action works

#### Zigbee2MQTT

- [ ] (**older devices**) You have ensured legacy is off/false for the device in the Z2M devices Settings (specific) page and that your actions matches those with legacy off?

Switch does have a "hold (released)" for top and bottom button, but both trigger the same ZHA event, so cannot be reliably mapped.

### CODE REVIEW

**Comment by Sian-Lee-SA** [comment]
Image needs to be cropped properly

**Comment by nwithan8** [comment]
> Image needs to be cropped properly

It has been cropped properly. That nub at the top is part of the product: https://www.ikea.com/us/en/p/rodret-wireless-dimmer-power-switch-smart-white-80559800/

**Comment by Sian-Lee-SA** [comment]
Not sure what the nub at top has to do with cropping properly, as stated in the "rules" for a PR, it needs to be cropped to the device edges. The x/sides are no where near the device and the top and bottom still has padding from the device

**Comment by Sian-Lee-SA** [comment]
There is also a nice image and blueprint for this device in the repo using Zigbee2MQTT (zigbee2mqtt-ikea-e2201). I would suggest ussing those resources and convert for ZHA

**Comment by Sian-Lee-SA** [comment]
Cheers

**Pull request merged**
