### PR TITLE
Added Shelly 1, 2.5, and Plus 2PM

### PR DESCRIPTION
**Pull request by peedub**
Added blueprints for Shelly 1, 2.5, and Plus 2PM. Generic images of switches have been used.

## Blueprint Checklist

- [x] You viewed the README and conformed to the [naming conventions](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#title-naming-convention)
- [x] You ordered the actions as stated in the README [action order](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#order-convention)
- [x] All filenames are lowercase and uses '-' for spaces and **not** '_' while using {service-name}-{switch-name-or-type}.yaml format
- [x] Images are png
- [x] Image backgrounds are transparent and is cropped to the device boundries
- [x] Images has a maximum width of 800px and maximum height of 500px
- [x] There are no missing buttons or actions
- [x] You have tested your blueprints and made sure each button and action works

### CODE REVIEW

**Comment by Sian-Lee-SA** [comment]
You've tested this and it all works?

**Comment by Sian-Lee-SA** [comment]
From what I can see, you have a yaml condition problem. when you do a press or hold it will fire both because you didn't define the conditions as an array, instead the below key and value will override the ones above.. Further more if the button being pushed and theres a value to check against for the button, then it should go in the button condition and not action

**Comment by peedub** [comment]
Thanks. Have made those corrections to the shelly 2.5 and shelly plus 2pm files. You're right, when I pushed the button, the lights would turn on then off. I had only tested it properly with the shelly 1 code.

**Comment by Sian-Lee-SA** [comment]
That looks better :) thanks for bringing in the first Shelly products!

**Pull request merged**
