### PR TITLE
Add ZHA blueprint for Aqara H1 Rotary Dimmer

### PR DESCRIPTION
**Pull request by nwithan8**
## Blueprint Checklist

- [x] You viewed the README and conformed to the [naming conventions](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#title-naming-convention)
- [x] You ordered the actions as stated in the README [action order](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#order-convention)
- [x] All filenames are lowercase and uses '-' for spaces and **not** '_' while using {service-name}-{switch-name-or-type}.yaml format
- [x] Images are png
- [x] Image backgrounds are transparent and is cropped to the device boundries
- [x] Images has a maximum width of 800px and maximum height of 500px
- [x] There are no missing buttons or actions
- [x] Your integration/service is running on the latest version
- [x] You have tested your blueprints and made sure each button and action works

Requires custom ZHA quirk: https://gist.github.com/oxc/754d6436ce62d92af660d3671acd9346

#### Zigbee2MQTT

- [ ] (**older devices**) You have ensured legacy is off/false for the device in the Z2M devices Settings (specific) page and that your actions matches those with legacy off?

### CODE REVIEW

**Comment by Sian-Lee-SA** [comment]
Please fix the image and change the conditions to key value pairs. Will reopen when done

**Comment by nwithan8** [comment]
> Please fix the image and change the conditions to key value pairs. Will reopen when done

Key-value pairs won't work on sub-keys for command arguments.

**Comment by Sian-Lee-SA** [comment]
They should eg.

```yaml
- key: command 
  value: 'stop_rotation'
- key: args.rotation_direction
  value: -1
```

Also make sure you're using latest version

**Comment by nwithan8** [comment]
I have tested it with the key-value pairs as you suggested, but I cannot get it to detect the data correctly.

My configuration:
```yaml
      - title: Rotate Left
        conditions: # "{{ data.command == 'stop_rotation' and data.args.rotation_direction == -1 }}"
          - key: command
            value: stop_rotation
          - key: args.rotation_direction
            value: -1
      - title: Rotate Right
        conditions: # "{{ data.command == 'stop_rotation' and data.args.rotation_direction == 1 }}"
          - key: command
            value: stop_rotation
          - key: args.rotation_direction
            value: 1
```

Debugging output (dev console):
image

The previous method of conditions I had did work properly.

I am using the latest version (v1.2.1).

Please advise.

**Comment by Sian-Lee-SA** [comment]
Ok, I'll have to investigate and fix the issues while using the data screenshot provided after merging. A couple issues needs to be addressed first.

- The image still needs to be cropped to the edges of the device
- Titles needs to be all lowercase
- Single buttons shouldn't have any shapes assigned ( "d: M 155 250 A 1 1 0 0 0 344 250 A 1 1 0 0 0 155 250" is redundant ), I'm also surprised it didn't error out due to being only one button with a shape property (I'll have to investigate this aswell).
- `press 1x` just needs to be `press`

**Comment by nwithan8** [comment]
> I'm also surprised it didn't error out due to being only one button with a shape property.

It does, discovered that yesterday, fixed it locally, will include that all in my PR

**Comment by nwithan8** [comment]
Should I open a new PR now that the concerns have been addressed, or will it not be merged due to the "command" issue?

**Comment by Sian-Lee-SA** [comment]
Just update the changes with this PR and I will merge this

**Comment by nwithan8** [comment]
I have pushed the changes to the branch associated with this PR, but since this PR is closed, they do not reflect in this PR. You would have to reopen this PR.

**Comment by nwithan8** [comment]
Following up on this @Sian-Lee-SA

**Comment by Sian-Lee-SA** [comment]
Sorry missed the notifications for this previously

**Comment by nwithan8** [comment]
@Sian-Lee-SA so, is this PR going to be reopened?

**Comment by Sian-Lee-SA** [comment]
Nope, I assume it was merged elsewhere as I can't reopen

**Pull request closed without merging**
