### PR TITLE
Added ZHA Ikea Styrbar

### PR DESCRIPTION
**Pull request by robotanik**
- [x ] You viewed the README and conformed to the [naming conventions](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#title-naming-convention)
- [ x] You ordered the actions as stated in the README [action order](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#order-convention)
- [x ] All filenames are lowercase and uses '-' for spaces and **not** '_' while using {service-name}-{switch-name-or-type}.yaml format
- [ x] Images are png
- [ x] Image backgrounds are transparent and is cropped to the device boundries
- [ x] Images has a maximum width of 800px and maximum height of 500px
- [x ] There are no missing buttons or actions
- [x ] Your integration/service is running on the latest version
- [ x] You have tested your blueprints and made sure each button and action works

### CODE REVIEW

**Comment by Sian-Lee-SA** [comment]
Just rename 'release' to 'hold (released)' then I can merge.

**Comment by robotanik** [comment]
One annoying thing is that the device always sends a turn on command (top button) when holding the left or right button. There is no difference between this and pressing the top button in the event data. Is there a way to ignore an event by the previous event?

**Comment by Sian-Lee-SA** [comment]
This is an internal issue in the actually firmware (I can't wrap my head around their thinking when they designed it). As it is in the manual for the device, So for an end user, they should be aware this is the expected behaviour... Due to their coding, there's no way to differentiate the buttons because internall it acts as the top button when holding left or right,,, it's stupid but that's Ikea

**Comment by Sian-Lee-SA** [comment]
your titles are wrong.. it should be press -> hold -> hold (released)... there should be no `release`

**Comment by robotanik** [comment]
Is everything fine now for the pull?

**Comment by Sian-Lee-SA** [comment]
Thanks

**Pull request merged**
