### PR TITLE
Added Zigbee2MQTT EnOcean PTM 215Z

### PR DESCRIPTION
**Pull request by Llewe**
## Blueprint Checklist

- [x] You viewed the README and conformed to the [naming conventions](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#title-naming-convention)
- [x] You ordered the actions as stated in the README [action order](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#order-convention)
- [x] All filenames are lowercase and uses '-' for spaces and **not** '_' while using {service-name}-{switch-name-or-type}.yaml format
- [x] Images are png
- [x] Image backgrounds are transparent and is cropped to the device boundries
- [x] Images has a maximum width of 800px and maximum height of 500px
- [ ] There are no missing buttons or actions
- [x] Your integration/service is running on the latest version
- [x] You have tested your blueprints and made sure each button and action works

#### Zigbee2MQTT

- [x] (**older devices**) You have ensured legacy is off/false for the device in the Z2M devices Settings (specific) page and that your actions matches those with legacy off?

## Additional info

- Device: https://www.zigbee2mqtt.io/devices/PTM_215Z.html
- Product image is from the `Gira/Senic Friends of Hue Switch` model (white label solution, therefore the outside of the switch can look different).

### Missing action: `press_energy_bar`
I didn't add this action because I have no idea how to trigger it. It is not visible from the outside. But its listed in zigbee2mqtt

### Buttons
The switch buttons of this device are in this order
1 | 3
-- | -- 
2 | 4

Since there is an action for pressing/releasing 1&3 and 2&4 I decided to add two additional buttons in the GUI.
1&3 above and 2&4 below the individual buttons.

This model doesn't support an `hold` action but is has a `press` and a `release` action. I'm not sure if i got the naming conventions of this project right.

### CODE REVIEW

**Comment by platini76** [comment]
https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/issues/104#issuecomment-1447378552

**Comment by Llewe** [comment]
sorry i had only seen that your issue was closed not that you are working on it.

If you have any suggestions for improvement, please feel free to submit them. Most of the changes should be quite easy to implement in the yml

**Comment by Sian-Lee-SA** [comment]
Initial press should be init and post press would be a normal press so the actions should go init->press. Also a space before the ( in the title makes it cleaner to read. Other than that, looks fine to me.

**Comment by Sian-Lee-SA** [comment]
Also take a look at Zigbee2MQTT / Xiaomi Double Key (WXKG07LM). If you can get the multiple press to look similiar with a circle art instead then that would be great too.

**Comment by Llewe** [comment]
Oh i missed the part with the double btns in the readme.

I also changed the coordinates of the button boxes a little bit so that there is no gap between them.
Looks like this now:

image

**Comment by Sian-Lee-SA** [comment]
Thank You! looks good

**Pull request merged**
