### PR TITLE
Added Shelly 1pm Mini Gen 3

### PR DESCRIPTION
**Pull request by cemilbrowne**
Added support for Shelly 1pm Mini Gen 3
## Blueprint Checklist

- [X] You viewed the README and conformed to the [naming conventions](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#title-naming-convention)
- [X] You ordered the actions as stated in the README [action order](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#order-convention)
- [X] All filenames are lowercase and uses '-' for spaces and **not** '_' while using {service-name}-{switch-name-or-type}.yaml format
- [X] Images are png
- [X] Image backgrounds are transparent and is cropped to the device boundries
- [X] Images has a maximum width of 800px and maximum height of 500px
- [X] There are no missing buttons or actions
- [X] Your integration/service is running on the latest version
- [X] You have tested your blueprints and made sure each button and action works

### CODE REVIEW

**Comment by Sian-Lee-SA** [comment]
Same deal as to my response to your other PR

**Comment by cemilbrowne** [comment]
OK; I tweaked the two settings here.  On the Moes one, it was already tap and I reused image - I think that one is good to go potentially?

**Comment by Sian-Lee-SA** [comment]
I completely understand and sorry for the sudden late change, I literally renamed all the blueprints from tap to press after presenting it to you to do the same. Everything looks fine, Cheers. In regards to the image, I generally get authors to tighten their images and avoid any padding but I probably let that one slide because it's pretty close and I was just in a "whatever" mood but in that regards as it is a copy, i can't expect you to change it and look different to the original so it's fine.

**Comment by cemilbrowne** [comment]
Thanks for creating this add-on, glad I could contribute!

**Pull request merged**
