### PR TITLE
Adding Moes Smart Knob AKA ERS-10TZBVK-AA 

### PR DESCRIPTION
**Pull request by bleughb**
## Blueprint Checklist

- [x] You viewed the README and conformed to the [naming conventions](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#title-naming-convention)
- [x] You ordered the actions as stated in the README [action order](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#order-convention)
- [x] All filenames are lowercase and uses '-' for spaces and **not** '_' while using {service-name}-{switch-name-or-type}.yaml format
- [x] Images are png
- [x] Image backgrounds are transparent and is cropped to the device boundries
- [x] Images has a maximum width of 800px and maximum height of 500px
- [x] There are no missing buttons or actions
- [x] Your integration/service is running on the latest version
- [x] You have tested your blueprints and made sure each button and action works

#### Zigbee2MQTT

- [x] (**older devices**) You have ensured legacy is off/false for the device in the Z2M devices Settings (specific) page and that your actions matches those with legacy off?

### CODE REVIEW

**Comment by bleughb** [comment]
cropped image as requested and changed titles to lower case

**Comment by Sian-Lee-SA** [comment]
Titles should be named press, not click

**Comment by imbackniantic** [comment]
Can you please merge this branch in order to use the moes knob through switch manager? Thanks!

**Comment by Sian-Lee-SA** [comment]
> Can you please merge this branch in order to use the moes knob through switch manager? Thanks!

Will merge when changes are made... You can just use his blueprint as is by just copying the blueprint from his repo and placing in the homessistant blueprints path.

Closing this as no changes has been made.

**Pull request closed without merging**
