### PR TITLE
Add support for GoControl WA00Z-1

### PR DESCRIPTION
**Pull request by francais01**
Support for this 2 button controller: https://www.gocontrol.com/detail.php?productId=12

## Blueprint Checklist

- [x] You viewed the README and conformed to the [naming conventions](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#title-naming-convention)
- [x] You ordered the actions as stated in the README [action order](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#order-convention)
- [x] All filenames are lowercase and uses '-' for spaces and **not** '_' while using {service-name}-{switch-name-or-type}.yaml format
- [x] Images are png
- [x] Image backgrounds are transparent and is cropped to the device boundries
- [x] Images has a maximum width of 800px and maximum height of 500px
- [x] There are no missing buttons or actions
- [x] Your integration/service is running on the latest version
- [x] You have tested your blueprints and made sure each button and action works

### CODE REVIEW

**Comment by francais01** [comment]
Double-checking my image, it looks like I could make rounded transparent corners on it (the device has rounded corners.) Would you like me to do that?

**Comment by Sian-Lee-SA** [comment]
Yes please, finer details are always welcomed, I also find just about every switch has some kind of roundness aswell so it would match the others in appearance

**Comment by francais01** [comment]
Replaced png with some rounded transparency on the corners. Cleaned up history so that there's just one commit.

**Comment by Sian-Lee-SA** [comment]
Awesome, Thank You!

**Pull request merged**
