### PR TITLE
added link to smart-live.net youtube demonstration video

### PR DESCRIPTION
**Pull request by miggi92**
added link to the readme of a german demonstration video on youtube.

https://www.youtube.com/watch?v=EEFMxeXMd1Q

### CODE REVIEW

**Comment by Sian-Lee-SA** [comment]
I appreciate your contribution on helping with your YouTube channel, but I won't go down the rabbit hole in adding external links to sources that are not my own or I have not had dealings with personally, Once I accept links like this, the expectations by anyone else just wanting to advertise themselves will get messy.

**Comment by Sian-Lee-SA** [comment]
I had just watched your video and there are a couple of incorrect statements here and there but nothing major. The problems I mostly found is in the comments section and the advice to use "Device Actions". There is a big warning right ontop of the github page (README.md) for this repo that says 

"Warning

The device sequence action is currently unsupported, use service/action calls instead as this should be used thoughout Home Assistant anyway. You can read more on why you shoudn't use it [here](https://community.home-assistant.io/t/why-and-how-to-avoid-device-ids-in-automations-and-scripts/605517)"

Please do not advise anyone to use Device actions and always normal actions instead as they do anything and everything device actions can do. If you want to increase or decrease brightness, just use light,turn_on with the property values Brightness step (brightness_step_pct) and so forth, This applies to Home Assistant throughout and isn't advised to use device actions at all... The iterator error that is shown in your comments is also related to them using Device actions.... Other than that, nice video

**Comment by miggi92** [comment]
Actually it's not my YouTube channel. I just saw this video in my feed today. 

I understand your points. 
I just thought it could be nice to find these links in the repository.

**Comment by Sian-Lee-SA** [comment]
> Actually it's not my YouTube channel. I just saw this video in my feed today.

I started to get that vibe after I sent the messages lol. Eitherway thanks for understanding

**Comment by miggi92** [comment]
> I had just watched your video and there are a couple of incorrect statements here and there but nothing major. The problems I mostly found is in the comments section and the advice to use "Device Actions". There is a big warning right ontop of the github page (README.md) for this repo that says 
> 
> "Warning
> 
> The device sequence action is currently unsupported, use service/action calls instead as this should be used thoughout Home Assistant anyway. You can read more on why you shoudn't use it [here](https://community.home-assistant.io/t/why-and-how-to-avoid-device-ids-in-automations-and-scripts/605517)"
> 
> Please do not advise anyone to use Device actions and always normal actions instead as they do anything and everything device actions can do. If you want to increase or decrease brightness, just use light,turn_on with the property values Brightness step (brightness_step_pct) and so forth, This applies to Home Assistant throughout and isn't advised to use device actions at all... The iterator error that is shown in your comments is also related to them using Device actions.... Other than that, nice video

Thanks you for this explanation!

**Pull request closed without merging**
