### PR TITLE
Added Zigbee2MQTT TuYa 1 and 2 gang remotes

### PR DESCRIPTION
**Pull request by Mr-Groch**
## Blueprint Checklist

- [x] You viewed the README and conformed to the [naming conventions](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#title-naming-convention)
- [x] You ordered the actions as stated in the README [action order](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#order-convention)
- [x] All filenames are lowercase and uses '-' for spaces and **not** '_' while using {service-name}-{switch-name-or-type}.yaml format
- [x] Images are png
- [x] Image backgrounds are transparent and is cropped to the device boundries
- [x] Images has a maximum width of 800px and maximum height of 500px
- [x] There are no missing buttons or actions
- [x] You have tested your blueprints and made sure each button and action works

### CODE REVIEW

**Comment by Mr-Groch** [comment]
This is PR without switches - just normal remotes with standard Z2M action topic

**Comment by Mr-Groch** [comment]
Its not duplicate - I've created this PR for only those remotes that works similar to all other blueprints, so it can be quickly added - I think that switch modules will need some other work...

**Comment by Sian-Lee-SA** [comment]
The same files are in your other PR, you shouldn't create multiple PR's with the same files

**Comment by Mr-Groch** [comment]
Can we reopen this? Those remotes are working fine. Switch modules are on seperate branch but created from this base, do

**Comment by Mr-Groch** [comment]
Can we reopen this? Those remotes are working fine. Switch modules are on seperate branch but created from this base, so that's why there and here are duplicates. If this will be merged, those duplicates will disapear becouse IT is based on same base commit

**Comment by Sian-Lee-SA** [comment]
I will Merge it just to knock it out of the way but I prefer one PR for anything coming from an author or it starts getting messy. For example the conversation on the other PR is relating to commits in this PR and so on. Secondly, I will crop this for you but I do hope you take the time in the future to find a decent photo editing software and crop before making a PR. Thanks

**Pull request merged**
