### PR TITLE
Added Zigbee2MQTT Trust Remote Control

### PR DESCRIPTION
**Pull request by Mr-Groch**
I didn't check 'There are no missing buttons or actions', becouse there is attribute 'action_group' in device main topic that changes after pressing button with bulb icon (or with 2 bulbs - that means 'all groups') - there is no seperate subtopic for that so it can't be mapped here... This device is meant to be controlling many other devices depending on action_group selected, but I don't know how to make this in this integration...

## Blueprint Checklist

- [x] You viewed the README and conformed to the [naming conventions](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#title-naming-convention)
- [x] You ordered the actions as stated in the README [action order](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#order-convention)
- [x] All filenames are lowercase and uses '-' for spaces and **not** '_' while using {service-name}-{switch-name-or-type}.yaml format
- [x] Images are png
- [x] Image backgrounds are transparent and is cropped to the device boundries
- [x] Images has a maximum width of 800px and maximum height of 500px
- [ ] There are no missing buttons or actions
- [x] You have tested your blueprints and made sure each button and action works

### CODE REVIEW

**Comment by Sian-Lee-SA** [comment]
That's fine, generally Zigbee operates within it's own ecosystem aswell as using groups to bind to buttons etc within the Zigbee protocol. So I always encourage to manage your switches within their ecosystems (Zigbee or Z-Wave) for control as this is more stable and more responsive. Switch Manager is generally the after thought and act's from buttons not mapped through other ecosystems.

**Comment by Sian-Lee-SA** [comment]
Are you able to send the mqtt topics and payloads for this device. Just out of curiosity

**Comment by Mr-Groch** [comment]
This is main device topic and payload:
image

Here device topic tree:
image

**Comment by Sian-Lee-SA** [comment]
Thanks, I was just wondering and exploring the action_group and was curious as to why my TRADFRI Styrbar had it aswell but it's just an internal thing within the zigbee network when the switch is bound to a zigbee group.

**Comment by Mr-Groch** [comment]
Here it's not only internal thing - action group exists even when remote is not bounded to group - there is 6 constant values changing when you change selected number on remote (there is led below 1-5 labels) - after pressing button with bulb icon, no action is send to z2m, but action_group is changing - I'm using this action_group property as condition in my HA automation to choose with device to control, for example in pseudo code:

```
switch action_group:
  case 18686: if button_pressed = on: turn_on light.ceiling
  case 18687: if button_pressed = on: turn_on light.small_lamp
```

It would be nice to have this possibility in switch manager also, but there is no possibility to use that action_group possibility now... Only within action sequence as condition based on HA entity state (action_group is exposed by z2m as entity)

**Comment by Sian-Lee-SA** [comment]
Can you be sure that group number is hardcoded for that device? I don't think it is, I think based on those numbers and what I have read, it's generated as it's group id so when something wants to bind to that group, they use that id within the zigbee network. That's how I understand it atm. It would also mean everyones setup would have different group ids

**Comment by Mr-Groch** [comment]
I'm not sure - I have only one device. But those numbers never changed - even after resetting remote, when I have changed my zigbee coordinator and needed to repair all devices.

**Comment by Sian-Lee-SA** [comment]
The devices themselves have these groups id's and settings integrated. It's how Zigbee can communicate with devices and groups without a bridge

**Comment by Sian-Lee-SA** [comment]
An alternative for your setup is node red and contstructing your own MQTT payloads. something to think about for your own setup

**Pull request merged**
