### PR TITLE
Added ZHA 1 & 2 gang version of Aqara D1 switch

### PR DESCRIPTION
**Pull request by Julien-Decoen**
## Blueprint Checklist

- [x] You viewed the README and conformed to the [naming conventions](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#title-naming-convention)
- [x] You ordered the actions as stated in the README [action order](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#order-convention)
- [x] All filenames are lowercase and uses '-' for spaces and **not** '_' while using {service-name}-{switch-name-or-type}.yaml format
- [x] Images are png
- [x] Image backgrounds are transparent and is cropped to the device boundries
- [x] Images has a maximum width of 800px and maximum height of 500px
- [x] There are no missing buttons or actions
- [x] Your integration/service is running on the latest version
- [x] You have tested your blueprints and made sure each button and action works

#### Zigbee2MQTT

- [ ] (**older devices**) You have ensured legacy is off/false for the device in the Z2M devices Settings (specific) page and that your actions matches those with legacy off?

### CODE REVIEW

**Comment by Lakitna** [comment]
Aqara has different model switches, it's probably a good idea to specify this in your blueprints. For example, I just opened a PR for different Aqara switches: #122

**Comment by Sian-Lee-SA** [comment]
A good source for reference would be https://www.zigbee2mqtt.io/supported-devices/ and find you device then use the model and description to help name your blueprints

**Comment by Julien-Decoen** [comment]
Looks better, thanks :)

**Comment by Sian-Lee-SA** [comment]
What is default_sequence? this isn't a valid key

**Comment by Sian-Lee-SA** [comment]
Will close this until the invalid keys are removed

**Comment by Julien-Decoen** [comment]
Oupsy. I made a little piece of code to give a default sequence from blueprint on my fork. But I forgot to delete it for the PR. I made changes.

**Comment by Julien-Decoen** [comment]
Should I re-open it ? Or make another one ?

**Comment by Sian-Lee-SA** [comment]
Just reopened for you, just update this PR with the changes then I can merge :)

**Pull request merged**
