### PR TITLE
Added deCONZ Ikea Trådfri Shortcut

### PR DESCRIPTION
**Pull request by johro897**
## Blueprint Checklist

- [x] You viewed the README and conformed to the [naming conventions](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#title-naming-convention)
- [x] You ordered the actions as stated in the README [action order](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#order-convention)
- [x] All filenames are lowercase and uses '-' for spaces and **not** '_' while using {service-name}-{switch-name-or-type}.yaml format
- [x] Images are png
- [x] Image backgrounds are transparent and is cropped to the device boundries
- [x] Images has a maximum width of 800px and maximum height of 500px
- [x] There are no missing buttons or actions
- [x] You have tested your blueprints and made sure each button and action works

### CODE REVIEW

**Comment by Sian-Lee-SA** [comment]
Are you sure  identifier key is `id`? all other deCONZ blueprints use `device_id`

**Comment by johro897** [comment]
I guess it depends on what you are using as ID. I used the name given in deCONZ. What is preffered?
device_ID is not as recognicable for use I would say

event_type: deconz_event
data:
  id: poolen
  unique_id: 94:de:b8:ff:fe:15:06:47
  event: 1002
  device_id: b80f4b6025ff71012fc44c2d90f565cd
origin: LOCAL
time_fired: "2023-01-04T19:55:48.782137+00:00"
context:
  id: 01GNZ5NA5ES2BA9RBQ4WHJCP4W
  parent_id: null
  user_id: null

**Comment by Sian-Lee-SA** [comment]
Hmm, I would say because device_id has been the norm atm then to use that instead. Preferrably I guess one that is easily swapped incase a device dies and needs to be replaced so I guess id would be better. Now I deliberate whether to change the other blueprints...

**Comment by Sian-Lee-SA** [comment]
Thank You!

**Comment by Sian-Lee-SA** [comment]
Just out of curiosity, is it possible that id could be empty if a name wasn't sent in deCONZ? I remember when I used deCONZ a while ago that some added devices would show their address instead of a name

**Comment by johro897** [comment]
> Just out of curiosity, is it possible that id could be empty if a name wasn't set in deCONZ? I remember when I used deCONZ a while ago that some added devices would show their address instead of a name which in this case device_id would be preferred

Not sure, But if memory serves me right there is always a name given when adding to deCONZ.

**Pull request merged**
