### PR TITLE
Added Zigbee2MQTT TuYa Scene ts0046 and ss6400

### PR DESCRIPTION
**Pull request by sammcj**
Add Tuya 4 and 6 scene switches.

- ts0046
- ss6400
- https://www.aliexpress.com/item/1005004988714663.html

## Blueprint Checklist

- [x] You viewed the README and conformed to the [naming conventions](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#title-naming-convention)
- [x] You ordered the actions as stated in the README [action order](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#order-convention)
- [x] All filenames are lowercase and uses '-' for spaces and **not** '_' while using {service-name}-{switch-name-or-type}.yaml format
- [x] Images are png
- [x] Image backgrounds are transparent and is cropped to the device boundries
- [x] Images has a maximum width of 800px and maximum height of 500px
- [x] There are no missing buttons or actions
- [x] Your integration/service is running on the latest version
- [x] You have tested your blueprints and made sure each button and action works

### CODE REVIEW

**Comment by Sian-Lee-SA** [comment]
Thanks, just need the images cropped to the devices edges (this can be acheived in photoshop by ctrl clicking the thumbnail in the layers panel then going to images->crop). Other than that it all looks good.

**Comment by sammcj** [comment]
Oh whoops, I forgot to re-crop after I added the transparency - done now and re-homed x/y.

**Comment by sammcj** [comment]
Screenshots for reference

SCR-20230128-ml7

SCR-20230128-ml7-2

**Comment by Sian-Lee-SA** [comment]
Perfect thank you, Reason I get contibuters to crop to the edges is because 1. consistency and 2. because if I decide later to add padding via CSS then it squishes the non cropped images more. But good work on getting good images!

**Comment by sammcj** [comment]
It was hard to get decent ones, I actually ended up using some from their website, then using [ML](https://www.pixelmator.com/blog/2019/12/17/all-about-the-new-ml-super-resolution-feature-in-pixelmator-pro/) to increase their size and clarity 🤣

**Pull request merged**
