### PR TITLE
Added Z-Wave Zooz Zen32

### PR DESCRIPTION
**Pull request by TKpizza**
## Blueprint Checklist

- [x ] You viewed the README and conformed to the [naming conventions](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#title-naming-convention)
- [x ] You ordered the actions as stated in the README [action order](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#order-convention)
- [ x] All filenames are lowercase and uses '-' for spaces and **not** '_' while using {service-name}-{switch-name-or-type}.yaml format
- [ x] Images are png
- [x ] Image backgrounds are transparent and is cropped to the device boundries
- [x ] Images has a maximum width of 800px and maximum height of 500px
- [x ] There are no missing buttons or actions
- [x ] You have tested your blueprints and made sure each button and action works

### CODE REVIEW

**Comment by Sian-Lee-SA** [comment]
Image is too high, should be 500px max height

**Comment by TKpizza** [comment]
Sorry I read it the opposite. Will fix soon

**Comment by TKpizza** [comment]
should be good now

**Comment by Sian-Lee-SA** [comment]
Looks good, Thank you!

**Pull request merged**
