### PR TITLE
Added Shelly 1 blueprints for installation with momentary button or rocker switch

### PR DESCRIPTION
**Pull request by robotanik**
## Blueprint Checklist

- [x ] You viewed the README and conformed to the [naming conventions](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#title-naming-convention)
- [x ] You ordered the actions as stated in the README [action order](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#order-convention)
- [x ] All filenames are lowercase and uses '-' for spaces and **not** '_' while using {service-name}-{switch-name-or-type}.yaml format
- [ x] Images are png
- [ x] Image backgrounds are transparent and is cropped to the device boundries
- [x ] Images has a maximum width of 800px and maximum height of 500px
- [x] There are no missing buttons or actions
- [ ] Your integration/service is running on the latest version
- [x ] You have tested your blueprints and made sure each button and action works

### CODE REVIEW

**Comment by Sian-Lee-SA** [comment]
For the switch, would it not be better to have separate on and off actions while also having init action?

**Comment by Sian-Lee-SA** [comment]
Also is there no event data that handles this instead of entity?

**Comment by robotanik** [comment]
Sadly the shelly.click event only fires when the input gets a high state. On a rocker switch it fires a long click for one of the state changes after the long click time. A separate action for from off to on or the other way would be a good option.

**Comment by robotanik** [comment]
Apparently the newer Shelly Plus modeles have an [event](https://www.home-assistant.io/integrations/shelly/#events) for button down and button up. But the first generation does not have this.

**Comment by Sian-Lee-SA** [comment]
I see a few problems with this. Firstly, state_changed is discouraged because in gerneral, it goes against the standard for (switches) but I understand this one is not a stateless switch so I can understand an entity for it (so even though it's an issue, I can still accept it as there's no other method to get the state). 

Secondly, Auto discovery would be very flakey if a user happens to have any entity change from on to off or vise versa which can happen quite alot (is there any other attribute or such to scope in on the device?).

I did a search about the button version and it seems to be a physical button device so I think using an image that represents the device would be desired. https://www.expert4house.com/690-large_default/shelly-button-1.jpg.

For single switches that is a module, I am starting to think an image of just the module would be more appropriate (I will probably update other switches that are just modules) but multiple buttoned modules should use a singular generic button image (not valid in this PR) (I also don't like the current image with the module in the corner of the switch as it causes too much padding, if it fits within the generic switch art and the switch itself is cropped to the borders then thats fine).

It's taken me a while to wrap my head around the shelly devices and how the author made the original blueprint without defining that it's a buttoned version because it was very unclear to me so that's why I have spend a while googling these devices....

I encourage to use key, value pairs where possible. So the actions for the switch should use the  `key and value` array but the root template conditions are fine as it makes sense there. You also don't need to check the old state in the actions as the root condition has already validated this. So checking the current condition will suffice. 

Lastly, toggle should be renamed to init as the init will be common language within this project to mean it will execute on any action which in this case it will for both on and off.

**Comment by Sian-Lee-SA** [comment]
Does the following not work?
```yaml
buttons:
  - actions:
      - title: init
      - title: 'on'
        conditions: 
          - key: new_state.state
            value: 'on'
      - title: 'off'
        conditions: 
          - key: new_state.state
            value: 'off'
```

**Comment by Sian-Lee-SA** [comment]
You mention the button one i showed a picture of is a different device, considering when that device gets added it would make sense to call it shelly 1 (button) as such so yours should probably be techincally a module shelly 1 button module or something alike... file names are more important in this aspect.

**Comment by robotanik** [comment]
> Does the following not work?

No. This does not work. Have you an idea why this does not work?

**Comment by robotanik** [comment]
The stand alone device is called [Shelly Button 1](https://www.shelly.cloud/en-de/products/product-overview/1xbtn1w) and the Module for installation is called [Shelly 1](https://www.shelly.cloud/en-de/products/product-overview/1xbtn1w). So depending of the installation on needs the `shelly-shelly1-buttonmodlue` or the `shelly-shelly1-switchmodule`. For the standalone device on could chose `shelly-shelly-button1`?

**Comment by Sian-Lee-SA** [comment]
I understand the module is an installation for the shelly button it's just for user convenience if they're unaware so they can choose the button as a prebuilt device (I would expect people to know once they're involved in these products but I'm sure there's some that doesn't know they're the same as they are technically sold as seperate products).

I will test a dummy event to see if it works but it should do. Will update once I figure out whats going on with that.

**Comment by Sian-Lee-SA** [comment]
Turns out that the event data handled through Python for state_change uses the state classes instead of a dictionary (pretty unique) and seeing as you're the first to do a blueprint involving state_change for an entity this has never popped up before. I will convert this in code to do a dictionary which will then allow the key and value pairs to work. After I post a new release, could you please confirm with the key value pairs works then I can merge. Thanks.

**Comment by robotanik** [comment]
Now it works. Thank you very much for the guidance and the quick answers.

**Comment by Sian-Lee-SA** [comment]
Thanks and thanks for your patience!

**Pull request merged**
