### PR TITLE
Added ZHA Tuya single and double switches (ts0041 and ts0042)

### PR DESCRIPTION
**Pull request by FreekFlakes**
## Blueprint Checklist

- [x] You viewed the README and conformed to the [naming conventions](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#title-naming-convention)
- [x] You ordered the actions as stated in the README [action order](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#order-convention)
- [x] All filenames are lowercase and uses '-' for spaces and **not** '_' while using {service-name}-{switch-name-or-type}.yaml format
- [x] Images are png
- [x] Image backgrounds are transparent and is cropped to the device boundries
- [x] Images has a maximum width of 800px and maximum height of 500px
- [x] There are no missing buttons or actions
- [x] Your integration/service is running on the latest version
- [x] You have tested your blueprints and made sure each button and action works

#### Zigbee2MQTT

- [x] (**older devices**) You have ensured legacy is off/false for the device in the Z2M devices Settings (specific) page and that your actions matches those with legacy off?

### CODE REVIEW

**Comment by hrw** [comment]
Nice! Recently added some of them at home.

**Comment by Sian-Lee-SA** [comment]
Titles need to match the guidelines noted in the readme of this repo

**Comment by FreekFlakes** [comment]
Updated titles to follow the naming convention (apologies for missing those)

**Comment by Sian-Lee-SA** [comment]
close 😉. [custom_components/switch_manager/blueprints/zha-tuya-2-gang-switch-ts0042.yaml](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/pull/216/files#diff-77f49e932bfd5eff9170f76faa43e114d5b5f86b9631a3612126cd593a16ab28) should be press 2x not x2

**Comment by FreekFlakes** [comment]
I seem to automatically type 'x2'. Now the titles are updated to the naming convention (again apologies)

**Comment by Sian-Lee-SA** [comment]
All looks good, Thanks!

**Pull request merged**
