### PR TITLE
Added TuYa 1 and 2 gang wall switch for Z2M

### PR DESCRIPTION
**Pull request by Mr-Groch**
This time there are 2 switches that Z2M doesn't publish action topic - instead it will publish in device topic state or state_left / state_right attribute with ON or OFF value. I've tested those switches and actions works, but discovery for them doesn't work and green highlight also doesn't. In Topic user must manually enter device topic (like zigbee2mqtt/some device)

## Blueprint Checklist

- [x] You viewed the README and conformed to the [naming conventions](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#title-naming-convention)
- [x] You ordered the actions as stated in the README [action order](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#order-convention)
- [x] All filenames are lowercase and uses '-' for spaces and **not** '_' while using {service-name}-{switch-name-or-type}.yaml format
- [x] Images are png
- [x] Image backgrounds are transparent and is cropped to the device boundries
- [x] Images has a maximum width of 800px and maximum height of 500px
- [x] There are no missing buttons or actions
- [x] You have tested your blueprints and made sure each button and action works

### CODE REVIEW

**Comment by Mr-Groch** [comment]
Here you can see in MQTT Explorer what it looks like

image

**Comment by Sian-Lee-SA** [comment]
You checked "Image backgrounds are transparent and is cropped to the device boundries" but your images aren't cropped. Please crop them first. Also what is the full topic you're showing in the image? What topics are within zigbee2mqtt/<device your using/. Change mqtt topic to zigbee2mqtt/+/+ and test discovery

**Comment by Mr-Groch** [comment]
About cropping - I've tested how it looks, and it looks best like that, I've tried few versions of this images:

image

Full topic for 2 gang switch modules is 'zigbee2mqtt/Włącznik światła - łazienka'

**Comment by Sian-Lee-SA** [comment]
It's just how I need things to conform. Code can change to add padding manually, And it clearly shows the image of the buttons are padded compared to the others. Eg the Sonoff is a bigger size to yours because of no padding

**Comment by Sian-Lee-SA** [comment]
Things need to conform and be the same across blueprints, going rogue and changing things becsause of personal taste no longer unifies the blueprints.

**Comment by Sian-Lee-SA** [comment]
After checking your MQTT topic and the mqtt result... You would want to do 

`mqtt_topic_format: zigbee2mqtt/+` for the modules then change the conditions keys from state to state_left or state_right depending on the button

**Comment by Sian-Lee-SA** [comment]
Further more I don't understand how it could be working when there is no "state" key in that topic. Are you sure you don't have an automation already hooked to that switch?

**Comment by Mr-Groch** [comment]
> After checking your MQTT topic and the mqtt result... You would want to do
> 
> `mqtt_topic_format: zigbee2mqtt/+` for the modules then change the conditions keys from state to state_left or state_right depending on the button

It's done this way from beginning - button actions are working

I've tried also with mqtt_topic_format: zigbee2mqtt/+/ and zigbee2mqtt/+/+ with no luck - discovery and green highlighting of pressed button doesnt work

**Comment by Mr-Groch** [comment]
> Further more I don't understand how it could be working when there is no "state" key in that topic. Are you sure you don't have an automation already hooked to that switch?

There are 2 switches - 1 gang with just state atribute and 2 gang with state_left and state_right (no state)

**Comment by Sian-Lee-SA** [comment]
Yh I was reading the first 1 gang

**Comment by Sian-Lee-SA** [comment]
After you have cropped the images then I can merge and I'll do some testing on it

**Comment by Mr-Groch** [comment]
I've cropped - look at commit [b4882029f212f9f8f32843cae2459f24d351c66a](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/pull/45/commits/b4882029f212f9f8f32843cae2459f24d351c66a)

image

**Comment by Sian-Lee-SA** [comment]
There is still padding. It states "Image backgrounds are transparent and is cropped to the **device boundries**"

**Comment by Sian-Lee-SA** [comment]
If using photoship, just ctrl click the layers thumb then goto image -> crop

**Comment by Mr-Groch** [comment]
I don't have any image editing software - I'm using online tools, so it is little frustrating. Especially path shape was difficult to me to generate...

**Comment by Sian-Lee-SA** [comment]
Gimp seems to be a good free alternative

**Comment by Sian-Lee-SA** [comment]
So it turns out the module versions are seperate switches, You also used a graphic that doesn't represent the module. Instead the module is hooked up seperately to a switch which means to have a left and right button, there would be 2 switches for the module blueprint. Next it can be correctly determined what switch was press based on the sub topics left and right. Right now the switch right now might work but it's firing twice because it's checked the values of but left_state and right_state in the same message.

**Comment by Sian-Lee-SA** [comment]
As you can see @ https://www.zigbee2mqtt.io/devices/TS0002_switch_module.html they are defined as 2 seperate switches and this makes sense because whatever is plugged in doesn't necessary mean it's hooked to the same interface.

**Comment by Mr-Groch** [comment]
Images are right. I know and see what's on my wall ;) In Z2M it is Discovery as TS0012 for 2 gang and TS0011 for 1 gang (https://www.zigbee2mqtt.io/devices/TS0012.html). Tuya devices generał problem is that three are lot of different looking devices but identifying with the same model id. Almost all my tuya switches are looking different In real that on Z2M thumbnail image. I have used Prosper images here

**Comment by Mr-Groch** [comment]
Remotes are discoveed as TS0041 and TS0042 for 1 gang and 2 gang - on Z2M atheee are also different images - same model id is used for touch switches and physical switches

**Comment by Mr-Groch** [comment]
I have also on my home switch module that looks same as You have posted - seperate module behind wall switch, only 1 gang and IT is also discoveed In Z2M as TS0011.

**Comment by Mr-Groch** [comment]
i van change file mame and title to remove Module from mame if You want. But the real problem is with discovery In Switch Manager and handling seperate topics for one device

**Comment by Sian-Lee-SA** [comment]
I'm fine with the gang's, I was talking about the modules which are wired up to external switches aren't they?

**Comment by Sian-Lee-SA** [comment]
I was also going off a google search on TuYa 2 Gang Switch Module. Whatever TuYa defines it as, I was just searching as to why they didn't have an action mqtt topic for the device which I discovered TuYa TS0003_switch_module as being the first hit. So I assumed TS0002 would be for the two button module instead of 3. As modules tend to be a wired up little device that sits behind a physical switch, So i have no idea what TuYa is doing here. Further more, I would question on Zigbee2MQTT as to why that device isn't sending an action topic

**Comment by Sian-Lee-SA** [comment]
I think adding the model id would be benificial but what I'm trying to wrap my head around is how I want to implement this because that device should be sending an action MQTT and as it stands now, the yaml isn't valid because the MQTT payload it's receiving is going to call both sides of the switch whether be on or off. To test this, you could set the switch for your current blueprint to call a service light.toggle and set both sides to a seperate light, then press on button and I'm sure the other will toggle too.

**Comment by Mr-Groch** [comment]
OK, I will add model id to names. This PR is dedicated to TS0011, and TS0012 as wall switches with builtin modules (pictures are accurate - I have exactly that white switches as on pictures in my home). There are also separate modules, that you need to wire to external wall switch - I have them also in my home, and they also are discovered as TS0011 and TS0012. So they work the same and can be used with one blueprint.

I will check later with that changing state bahoviour and I'll let you know. I saw that there was seperate subtopics for left and right for TS0012 (but no subtopic for TS0011) but don't know if there is also state published - will check that too

What about TS0041 and TS0042? They are battery powered remote switches with action topic and they are working fine (they have action topic) - maybe we can reopen PR #44 - there I have added only those remotes...

**Comment by Sian-Lee-SA** [comment]
It's the sub topics left and right that led me to believe that it was a wired module which would make sense because left could be set as one switch and right as a completely seperate switch which then could have their own MQTT topics independently and I would be ok with  that because it's not known if a multiple controlled wired up module is connected to the same physical switch. But after seeing your's it doesn't even come across as a module as such but just another physical switch as is.

**Comment by Mr-Groch** [comment]
OK, I've checked subtopics and button action behaviour.

First, I've defined actions for each button for on and off for 2 gang (TS0012), first button on/off was switching first lamp on/off, second button on/off was controlling other lamp in same room. Test result is that both button action won't interfere each other. Pressing on/off with left button won't activate second lamp, and pressing on/off with right button won't activate first lamp. So it is working as is, here is my configuration from .storage/switch_manager:

```
"4": {
        "name": "Włącznik światła - łazienka",
        "enabled": true,
        "blueprint": "zigbee2mqtt-tuya-2-gang-switch-module",
        "identifier": "zigbee2mqtt/Włącznik światła - łazienka",
        "buttons": [
          {
            "actions": [
              {
                "sequence": [
                  {
                    "service": "light.turn_on",
                    "data": {},
                    "target": {
                      "entity_id": "light.lampki_kuchnia"
                    }
                  }
                ],
                "mode": "single"
              },
              {
                "sequence": [
                  {
                    "service": "light.turn_off",
                    "data": {},
                    "target": {
                      "entity_id": "light.lampki_kuchnia"
                    }
                  }
                ],
                "mode": "single"
              }
            ]
          },
          {
            "actions": [
              {
                "sequence": [
                  {
                    "service": "light.turn_on",
                    "data": {},
                    "target": {
                      "entity_id": "light.lampa_kuchnia"
                    }
                  }
                ],
                "mode": "single"
              },
              {
                "sequence": [
                  {
                    "service": "light.turn_off",
                    "data": {},
                    "target": {
                      "entity_id": "light.lampa_kuchnia"
                    }
                  }
                ],
                "mode": "single"
              }
            ]
          }
        ]
      },
```

Next subtopics - don't know why but only for left button there is subtopic in mqtt with state attrubute. Right button doesn't have subtopic with state... But my first test showed that there is no need for seperate subtopics - it is working with main device topic.

But still - discovery and active button highlighting in switch manager editor doesn't works

**Comment by Sian-Lee-SA** [comment]
I honestly think someone has screwed up the switch at Zigbee2MQTT it's not following their standards and protocols

**Comment by Sian-Lee-SA** [comment]
Yep, I thought that would happen because you're getting both states in the same topic so the conditions will always pass both. There is also no way around this because we dont hold a previous state for a device, even if it was added as a generic automation in home assistant, it would still have the same issue.

**Comment by Sian-Lee-SA** [comment]
Like I said, I would be going to Zigbee2MQTT github page and request they fix these devices up

**Comment by Sian-Lee-SA** [comment]
The reason it didn't do it for the left button is because it was processed first and there was no need to process the other button where as the right button they would both get processed (same goes if there was a 3rd and 4th so on...)

**Comment by Mr-Groch** [comment]
So there is in general no way to handle properly z2m switches in switch manager - all z2m switches doesn't have individual subtopic for action, only state in main device topic. Only buttons in z2m have actions... Integration name is misleading in use with z2m then ;)

**Comment by Sian-Lee-SA** [comment]
I think because the switch was shipped with a module, they're using the module as the underlying entrypoint so they're disregarding the switch thats attached and resorting to the module device instead as to keep consistent with the core mechanics of the module. So far it seems the modules don't have actions or switches with a module being the core which like stated before can equate to 2 different switches

**Comment by Sian-Lee-SA** [comment]
"Integration name is misleading in use with z2m then ;)". If you're talking about Switch Manager name being misleading then I beg to differ, you can still manage those switches as seperate switches ;)

**Comment by Mr-Groch** [comment]
Single switches will also have false positives triggering - device topic will be updated occasionally by last_seen, linkquality or other attributes, so even if state will not change it can couse actions to fire in switch manager... Only solution is to remember last state for each button in switch manager and fire only when it will change

**Comment by Sian-Lee-SA** [comment]
So single switches don't have any subtopics?

**Comment by Mr-Groch** [comment]
No, as you can see in PR - 1 gang and 2 gang has both mqtt_topic_format: zigbee2mqtt/+ where in place of + is device name - in that topic is json published with all device attributes - single switches have only state, 2 gang state_left and state_right... No subtopics exists for single switch

**Comment by Mr-Groch** [comment]
> Remembering state wont change the fact that that information doesn't retain when Home Assistant is restarted.

Can you store it in .storage/switch_manager ?

**Comment by Mr-Groch** [comment]
This is how mqtt discovery look like for 2 gang and 1 gang switches:

2 gang left:
```
  "payload_off": "OFF",
  "payload_on": "ON",
  "state_topic": "zigbee2mqtt/0xbc33acfffefe2738",
  "value_template": "{{ value_json.state_left }}"
```
2 gang right:
```
  "payload_off": "OFF",
  "payload_on": "ON",
  "state_topic": "zigbee2mqtt/0xbc33acfffefe2738",
  "value_template": "{{ value_json.state_right }}"
```

1 gang:
```
  "payload_off": "OFF",
  "payload_on": "ON",
  "state_topic": "zigbee2mqtt/Przełącznik - subwoofer",
  "value_template": "{{ value_json.state }}"
```

And this is true for all other switches I have in Z2M, not only wall light switches

**Comment by Sian-Lee-SA** [comment]
Yh, that's pretty much creating a seperate entity for each button just like creating a switch for each... I think the best approach is to have a generic module switch under Zigbee2MQTT as one button then can be named Living Room Switch - Left and Living Room Switch - Right etc. this can be achieved simply by using the sub topics left and right as they only contain the state... But single button is a bit weird to not have a state topic or something in the sub domain

**Comment by Sian-Lee-SA** [comment]
Out of curiosity, do you have options to set how the switch acts in the expose tab on Zigbee2MQTT? it might be a simple setting you've missed

**Comment by Mr-Groch** [comment]
That the way z2m works... Most devices only has one main topic - state/device topic with all attributes. Only certain devices will have subtopics - like buttons have action

That separate subtopic just for left state in 2 gang is weird... But it might be related to my custom config - I've configured left button as light in z2m. My other devices that have state_left and state_right doesnt have any subtopics...

Maybe store state only for certain buttons, like switches from z2m in switch manager - new option that must be strictly enabled in blueprint

**Comment by Sian-Lee-SA** [comment]
Ummm, I've been using Zigbee2MQTT for over 2 years and have 5 different switches and there has been many switches added by other authors. I can assure you, thats not how Zigbee2MQTT works or "soley" because actions are defined for all those switches. I also recall reading that this was Zigbee2MQTT new standard to use an action sub topic (there's a reason it exists) it's possible that authors on Zigbee2MQTT for some TuYa devices hasn't updated their format. Who knows but at the end of the day you're welcome to fork this repo and make changes for your own system and tailor it for your needs. I'm going to close this PR because there's nothing further to be done and this convo has dragged on for a very long time.

You need to get in touch with Zigbee2MQTT because I'm not the one to answer questions related to their format as I clearly don't know what's going on with their methods.... If some devices (seems to be the majority) has an action sub topic yet some don't then it's a unification problem on their end that you need to investigate. I don't own these switches (modules) so it's not my place to chase it up,

**Comment by Mr-Groch** [comment]
Can you provide me some examples which switch device in z2m has action topic? I will try to investigate

**Comment by Sian-Lee-SA** [comment]
https://www.zigbee2mqtt.io/supported-devices/#e=action there's about 357 devices in that category that has action sub topic

**Comment by Sian-Lee-SA** [comment]
Now that I've had sleep and cleared my headm I realise the reason behind no action for your switch.... Simply put, it's meant to work the other wayaround. That switches job is to turn on whatever it's connected to, that's it's sequence and its job. It was never designed or programmed to handle anything thing is and effectively making it just a smart power outlet... You expecting the opposite from your device, when it's the other way around. The reason they made these modules and switches is to turn them on and off wireless which then displays it's current state (not action) because the switch isn't designed for handling other things. The idea from home assistant is to connect those switches as a generic light which then can toggle them on or off via automations etc. those devices aren't meant to go the otherway around. It's like saying creating a switch for my smart plug kettle to execute a sequence when I push the on button manually. That's not the idea behind them, the idea is to toggle them remotely.

**Comment by Mr-Groch** [comment]
Yes, you're right - thats the idea, but for me its not enough - I'm currently using it also like remotes for other devices, not just wired light (like when it is after sunset and switch is turned on, turn on also some other device).

I've found in that list some other wall swirches, very similar to my TuYa switches, with action topic, like this: 
https://www.zigbee2mqtt.io/devices/QBKG12LM.html

I'll will check converter for that xiami switch and maybe if I can handle will make PR to Z2M with updated TuYa switches with added action topic, like those Xiaomi switches

Thanks for help

**Comment by Mr-Groch** [comment]
Action topic will be added in next Z2M release. Here is my PR to zigbee-herdsman-converters that has been merged: https://github.com/Koenkk/zigbee-herdsman-converters/pull/5276 and here is merged pr to main zigbee2mqtt repo: https://github.com/Koenkk/zigbee2mqtt/pull/16106

**Comment by Sian-Lee-SA** [comment]
Glad you got that sorted through Z2M, much better solution imo

**Comment by Sian-Lee-SA** [comment]
Nice, I'll merge now but hope no one has issues trying to use it before Z2M makes the update and that they've also updated aswell. Oh well.

**Pull request merged**
