### PR TITLE
Add IKEA TRÅDFRI Remote to ZHA

### PR DESCRIPTION
**Pull request by nwithan8**
## Blueprint Checklist

Port of Z2M equivalent with [ZHA mappings](https://github.com/niro1987/homeassistant-config/blob/main/blueprints/automation/niro1987/zha_ikea_tradfri_5button_remote_custom.yaml)

Uses templates for conditions to capture args, following requirements as discussed in #139 

- [x] You viewed the README and conformed to the [naming conventions](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#title-naming-convention)
- [x] You ordered the actions as stated in the README [action order](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#order-convention)
- [x] All filenames are lowercase and uses '-' for spaces and **not** '_' while using {service-name}-{switch-name-or-type}.yaml format
- [x] Images are png
- [x] Image backgrounds are transparent and is cropped to the device boundries
- [x] Images has a maximum width of 800px and maximum height of 500px
- [x] There are no missing buttons or actions
- [x] Your integration/service is running on the latest version
- [x] You have tested your blueprints and made sure each button and action works

#### Zigbee2MQTT

- [ ] (**older devices**) You have ensured legacy is off/false for the device in the Z2M devices Settings (specific) page and that your actions matches those with legacy off?

### CODE REVIEW

**Comment by Sian-Lee-SA** [comment]
Image needs to be cropped to edge

**Comment by nwithan8** [comment]
> Image needs to be cropped to edge

This was reusing the existing image from the Z2M and deConz versions of this remote, so I was under the assumption it would be fine as is. Shall I edit the photos in the other configs at the same time?

**Comment by Sian-Lee-SA** [comment]
Probably slipped through from an earlier time

**Comment by nwithan8** [comment]
> Probably slipped through from an earlier time. If you were to edit, it would also need the buttons etc lined up. It's up to you but make sure the buttons and their behaviours stay the same

God bless this SVG tool and its "translate" option: https://yqnn.github.io/svg-path-editor/

**Comment by Sian-Lee-SA** [comment]
Thanks for that, glad you found a good tool. If using inkscape I probably would've just added the paths then nudged them over then copy paste the new values. Eitherway the editor seems quicker.

**Pull request merged**
