### PR TITLE
Added Zigbee2MQTT Philips Hue Smart Button

### PR DESCRIPTION
**Pull request by XavierG**
Zigbee2MQTT Philips Hue Smart Button blueprint

## Blueprint Checklist

- [x] You viewed the README and conformed to the [naming conventions](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#title-naming-convention)
- [x] You ordered the actions as stated in the README [action order](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#order-convention)
- [x] All filenames are lowercase and uses '-' for spaces and **not** '_' while using {service-name}-{switch-name-or-type}.yaml format
- [x] Images are png
- [x] Image backgrounds are transparent and is cropped to the device boundries
- [x] Images has a maximum width of 800px and maximum height of 500px
- [x] There are no missing buttons or actions
- [x] Your integration/service is running on the latest version
- [x] You have tested your blueprints and made sure each button and action works

### CODE REVIEW

**Comment by Sian-Lee-SA** [comment]
Looks good, thank you!

**Comment by Sian-Lee-SA** [comment]
I'm curious, is your blueprint configured to use the device with legacy on within Z2M? If so, this will need to be changed to match legacy off. The documentation on Z2M for this device has action names different to your blueprint and I believe this is because of the legacy being on.

**Comment by XavierG** [comment]
That's weird. I double checked, and legacy is off.
For some reason the z2mqtt page is unreachable:
https://www.zigbee2mqtt.io/devices/ROM001.html

What action did you identified ?

**Comment by Sian-Lee-SA** [comment]
https://www.zigbee2mqtt.io/devices/8718699693985.html is the page I'm referencing, but I'm not certain how they structure their actions and data based on legacy. Some devices has legacy default to on (which is the case for this device) so I'm not sure if their actions are based on legacy being on or not. It is confusing.

**Comment by XavierG** [comment]
Will do some testing when at home. I'm on a trip for the next couple of
days. Will keep you posted.

**Comment by XavierG** [comment]
Ok so, we it seems we are both right:

I tried with another button I have laying around, and unfortunately,
there is 2 different actions type for these buttons on long press:

*skip_backward / skip_upward* on one button, and *brightness_step_down
/ brightness_step_up* on another.

I also checked the model number in z2mqtt for both buttons, and it's the
same (8718699693985
<https://www.zigbee2mqtt.io/devices/8718699693985.html#philips-8718699693985>
).

To be honest, I don't know what to do in order to handle both types of
buttons. Any suggestions?

**Comment by XavierG** [comment]
Forgot to mention, the exact same firmware on both buttons too... So from
my point of view, there is no way to differentiate them...

**Comment by Sian-Lee-SA** [comment]
Are you checking the legacy off in the device pages settings (specific)? 
Screenshot_20230219-073544

**Comment by XavierG** [comment]
You're right! I forgot to check this!

So, my blueprint is correct when legacy set to false. But because it's true bu default, my 2nd try was working differently.

That being said, it means z2mqtt documentation listed Legacy actions. Shouldn't they list non legacy actions?

**Comment by Sian-Lee-SA** [comment]
You'd think so, honestly I've been trying to wrap my head around their docs and this legacy stuff for a while... I can only asssume because the default is true for the device, then they advertise the legacy actions because of the default but personally I find that logic counter intuitive. You'd think they should be encouraging the move from legacy and eventually deprecate it, so it could be a lack of updated documentation or resorting to the default in which legacy is on... One way or another, the legacy crap hasn't been handled well by them.

**Pull request merged**
