### PR TITLE
Added Z-WaveJS Zooz Zen71

### PR DESCRIPTION
**Pull request by TKpizza**
## Blueprint Checklist

- [x ] You viewed the README and conformed to the [naming conventions](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#title-naming-convention)
- [ x] You ordered the actions as stated in the README [action order](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#order-convention)
- [x ] All filenames are lowercase and uses '-' for spaces and **not** '_' while using {service-name}-{switch-name-or-type}.yaml format
- [x ] Images are png
- [ x] Image backgrounds are transparent and is cropped to the device boundries
- [ x] Images has a maximum width of 800px and maximum height of 500px
- [x ] There are no missing buttons or actions
- [x ] You have tested your blueprints and made sure each button and action works

### CODE REVIEW

**Comment by TKpizza** [comment]
I haven't tested yet as im not home. it works the same way as the zen72,76 and 77 so I just pushed this. i might not be able to test this so if someone let me know it works that would be great

**Comment by TKpizza** [comment]
Ok I was able to test it and it worked

**Comment by Sian-Lee-SA** [comment]
Just change the tile released to hold (released) then i can merge

**Comment by TKpizza** [comment]
done.

**Comment by Sian-Lee-SA** [comment]
Thank you!

**Pull request merged**
