### PR TITLE
Adding support for zigbee2mqtt Aqara Opple 3x2

### PR DESCRIPTION
**Pull request by Dunkelschunkel**
Tested locally with my on device
@Sian-Lee-SA: I also checked the docs from zigbee2mqtt [Aqara Opple 3x2](https://www.zigbee2mqtt.io/devices/WXCJKG13LM.html#action-enum) an it seems to work just fine.

Everything is based on the deconz blueprint for the same device as mentioned in [issue 78](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/issues/78)

## Blueprint Checklist

- [x] You viewed the README and conformed to the [naming conventions](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#title-naming-convention)
- [x] You ordered the actions as stated in the README [action order](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#order-convention)
- [x] All filenames are lowercase and uses '-' for spaces and **not** '_' while using {service-name}-{switch-name-or-type}.yaml format
- [x] Images are png
- [x] Image backgrounds are transparent and is cropped to the device boundries
- [x] Images has a maximum width of 800px and maximum height of 500px
- [x] There are no missing buttons or actions
- [x] Your integration/service is running on the latest version
- [x] You have tested your blueprints and made sure each button and action works

### CODE REVIEW

**Comment by Sian-Lee-SA** [comment]
The image isn't cropped to the device boundries.

**Comment by Sian-Lee-SA** [comment]
So I went ahead and changed the ones you copied from (I didn't realise they weren't cropped properly). I will do yours for you as it's fair to say you were just going by whats already in the repo

**Comment by Dunkelschunkel** [comment]
@Sian-Lee-SA thank you

**Comment by Dunkelschunkel** [comment]
@Sian-Lee-SA should I add the other, smaller aqara switches for zigbee2mqtt as well? I do not own any other than the 3x2 one but I assume they are similar.

**Comment by Sian-Lee-SA** [comment]
Just confirm with the zigbee2mqtt docs for the devices and what they have in their action sectio then I'll merge. Generally I would say no because I don't want the headaches of issues popping up about non working blueprints because it wasn't tested properly etc. But I'll let this one slide as they should be similar.

**Comment by Dunkelschunkel** [comment]
I'll check everything with the documentation at zigbee2mqtt and the blueprints from the deconz

Jan 26, 2023 10:56:46 AM Sian ***@***.***>:

**Comment by Sian-Lee-SA** [comment]
Also make sure you copy from the updated files in this repo as they're cropped and repositioned but not in a release yet

**Pull request merged**
