### PR TITLE
Added deCONZ Ikea Tradfri Remote and Aqara Wireless Mini Switch

### PR DESCRIPTION
**Pull request by splattner**
Adding:
- Ikea Tradfri Remote
- Aqara Wireless Mini Switch

via the deCONZ integration

### CODE REVIEW

**Comment by Sian-Lee-SA** [comment]
Thanks for contributing, unfortunately you created a pull request just as I'm doing naming conventions and cleanup to keep things consistent between blueprints and the Switch Manager interaction.

Could you just do a quick review of the README and reflect your blueprint to follow the naming and order conventions under Actions?

Could you also use detailed images instead of a diagram as this is more intuititive and appealing... I've found a couple of images that would fit perfectly.

https://med.greatecno.com/612932/xiaomi-aqara-wireless-mini-switch.jpg - This one would need to be cropped so there is no overhanging background. Also the blueprint for this does not need to define a shape or its position etc as it's only a single button. Lastly just mask out the background to be transparent

https://i.ytimg.com/vi/nk4D_cxjANs/maxresdefault.jpg - You can just crop the left remote and make the background transparent

Thanks!

**Comment by splattner** [comment]
sure, let me look into it

**Comment by splattner** [comment]
alright, I hope I got everything. I also changed the other deconz blueprints. Although the name have changes and I guess its breaking?
For the images, I took the existing SVG and just filled the background within the button with white, outside still transparent. Imho, they look nicer like this, instead of using existing photos. Hope you agree :)

**Comment by splattner** [comment]
ah, messed up the event ids while copy/paste the new action names. give me a sec :see_no_evil:

**Comment by splattner** [comment]
alright messup is fixed

**Comment by Sian-Lee-SA** [comment]
Oh sorry, I didn't realise you did the deconz aqara's lol... I just updated them about 20 minutes ago.

**Comment by splattner** [comment]
no worries, let me merge your changes

**Comment by Sian-Lee-SA** [comment]
While it might look nicer when everything else looks the same, it's just that all images are pictures so it looks a bit weird when you see a diagram drawing then a normal photo picture when selecting a blueprint imo. Not against the style just doesn''t really blend with the current images already being used.... I did want to point out the author for the aqara's (just coincidence that it happened to be you), that my changes would affect your setups once you decide to update the integration. So just be mindful of that. Also adding extra buttons or actions and remove them would invalidate users configs that are already using those blueprints so it's come to a point where things need to be set in stone and making sure the naming and stuff is adhered to to avoid future f*ck arounds.

**Comment by Sian-Lee-SA** [comment]
I'm still happy to merge with the images how you have them because that isn't set in stone, it's just that if a picture version happens to be merged the it will take preference, Nothing against it, it's just that pictures are take precedence over diagrams. sorry.

**Comment by Sian-Lee-SA** [comment]
Also there was an oversight in one of your aqara blueprints that I picked up when renaming everything and you accidently had an event for an action referencing the wrong button... Also should be press 2x and not press x2... fix that up then I can merge

**Comment by Sian-Lee-SA** [comment]
Just realised you used underscores for your file names... Now I have to fix that up... it should be '-'

**Comment by splattner** [comment]
sure, thats up to you. In my opinion, I don't really see a big style change, looks good in my opinion. So I won't spend more time in redoing the images, but its totally fine for me if someone want to.

Screenshot from 2023-01-01 17-03-17

press 2x and not press x2 is fixed and let me fix the underscore also.

No worries abount my setup, I will just redo my switch, Currently only 2 are created.

**Comment by splattner** [comment]
and the wrong referencing button in ikea tradfri is also fixed.
hope I got everything now and this is ready

**Comment by Sian-Lee-SA** [comment]
Screenshot 2023-01-02 025832

Definitely looks better against your black background I must admit... Will check the changes now

**Comment by Sian-Lee-SA** [comment]
Thanks heaps, Sorry to give you the run around but you did help me build a pull request template checkbox so been a big help regardless... 

It still shows on line 15 in [deconz-aqara-wireless-mini-switch.yaml](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/pull/36/files#diff-5fec9fe3218c74881eca96f5c5f00a8463b8633e9f088b7663f41a9384053d1e) press x2 but I'm happy to change that myself. Won't break anything.

CHEERS!

**Comment by splattner** [comment]
Awesome, thank you for this great component, glad I could help and thx for fixing the last x2 ;)

**Comment by Sian-Lee-SA** [comment]
I'm curious to your TRADFRI remote blueprint... Seems the middle button has one action without hold but I just had a user copy your blueprint and adapted for Zigbee2MQTT yet his version has an extra action (hold) action for the middle button. Did you miss this or does deconz not support a hold action for the middle button?

**Comment by splattner** [comment]
No, when I listen to the events in HA from deCONZ I only get the 1002 event (short release). Seems deCONZ does not support the hold action for the middle button. Not sure tough why, this would need more investigation in the deCONZ codebase I guess.

**Comment by Sian-Lee-SA** [comment]
Oh ok, all good. I actually loved deCONZ but resorted to Zigbee2MQTT in the end because of missing things, it's ashame thought because I prefer deCONZ over Zigbee2MQTT regarding everything else.

**Pull request merged**
