### PR TITLE
Added ZHA Sonoff SNZB-01 blueprint + some cleanup

### PR DESCRIPTION
**Pull request by pieterdevriesch**
- [x] You viewed the README and conformed to the [naming conventions](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#title-naming-convention)
- [x] You ordered the actions as stated in the README [action order](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#order-convention)
- [x] All filenames are lowercase and uses '-' for spaces and **not** '_' while using {service-name}-{switch-name-or-type}.yaml format
- [x] Images are png
- [x] Image backgrounds are transparent and is cropped to the device boundries
- [x] Images has a maximum width of 800px and maximum height of 500px
- [x] There are no missing buttons or actions
- [x] Your integration/service is running on the latest version
- [x] You have tested your blueprints and made sure each button and action works

I modified the Sonoff SNZB-01 blueprint from zigbee2mqtt to ZHA.

Also I changed the IKEA buttons to an SVG path so it will look better in the Switch Manager.

### CODE REVIEW

**Comment by Sian-Lee-SA** [comment]
They look alot better... Just need to be cropped right to the edges (no padding) though. First one (SNZB-01) is fine

**Comment by pieterdevriesch** [comment]
> 

Done. What do you mean with the last_button_state checking? Where are you seeing that?

**Comment by Sian-Lee-SA** [comment]
[custom_components/switch_manager/blueprints/zha-ikea-e1743.yaml](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/pull/130/files#diff-be937de00dc8702d6b457325db9dd1594bd79bc54c0f12977cfe3c6283531093) line 20

**Comment by pieterdevriesch** [comment]
> [custom_components/switch_manager/blueprints/zha-ikea-e1743.yaml](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/pull/130/files#diff-be937de00dc8702d6b457325db9dd1594bd79bc54c0f12977cfe3c6283531093) line 20 and 36

Ah that one. Well without using that variable you have no way of knowing which button was released, the top or bottom one, as they both give the exact same payload on release.

**Comment by Sian-Lee-SA** [comment]
Oh ok, that makes sense

**Pull request merged**
