### PR TITLE
Added Philips Hue Wall Switch

### PR DESCRIPTION
**Pull request by SebLi97**
## Blueprint Checklist

- [x] You viewed the README and conformed to the [naming conventions](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#title-naming-convention)
- [x] You ordered the actions as stated in the README [action order](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#order-convention)
- [ ] All filenames are lowercase and uses '-' for spaces and **not** '_' while using {service-name}-{switch-name-or-type}.yaml format
- [x] Images are png
- [ ] Image backgrounds are transparent and is cropped to the device boundries
- [x] Images has a maximum width of 800px and maximum height of 500px
- [x] There are no missing buttons or actions
- [x] Your integration/service is running on the latest version
- [x] You have tested your blueprints and made sure each button and action works

### CODE REVIEW

**Comment by Sian-Lee-SA** [comment]
Are there no actions for hold or anything else? Just wondering because Z2M for that device has a hold action aswell.

**Comment by robotanik** [comment]
I have tested one of my modules. If you configure it in the hue App to be a momentary button there is also the `repeat` type if you keep the button pressed an the `long_release` type after a longer press. If you configure it to be a rocker switch it only send a `initial_press` followed by a `short_release`. Also there is a subtype 2 for the second input, if there is a second input configured in the hue app.

**Comment by Sian-Lee-SA** [comment]
Ok, those will need to be added and best to put in info that elaborates that hold and hold (released) only works in rocker mode etc. The second input will also need to be added as a second button so a generic 2 button switch image will do (can just copy a 2 button generic image blueprint already available like tasmota-2-button-switch.png).

**Comment by SebLi97** [comment]
I have deleted the first wallswitch-files and added `philips-hue-wallswitch-single` and `philips-hue-wallswitch-double`. This shoud work!

**Comment by Sian-Lee-SA** [comment]
Images are not cropped properly "Image backgrounds are transparent and is cropped to the device boundries" also the filenames are not all lower case. 

Wall Switch is also two words

**Comment by SebLi97** [comment]
Fixed it!

**Comment by Sian-Lee-SA** [comment]
Thank you!

**Pull request merged**
