### PR TITLE
Added Zigbee2MQTT TS0042/LKWS211

### PR DESCRIPTION
**Pull request by KipK**
## Blueprint Checklist

- [x] You viewed the README and conformed to the [naming conventions](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#title-naming-convention)
- [x] You ordered the actions as stated in the README [action order](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#order-convention)
- [x] All filenames are lowercase and uses '-' for spaces and **not** '_' while using {service-name}-{switch-name-or-type}.yaml format
- [x] Images are png
- [x] Image backgrounds are transparent and is cropped to the device boundries
- [x] Images has a maximum width of 800px and maximum height of 500px
- [x] There are no missing buttons or actions
- [x] Your integration/service is running on the latest version
- [x] You have tested your blueprints and made sure each button and action works

#### Zigbee2MQTT

- [x] (**older devices**) You have ensured legacy is off/false for the device in the Z2M devices Settings (specific) page and that your actions matches those with legacy off?

There are 2 different yaml for this, booth have same form factors, but report different action over z2m.
TS0042 reports 1_single 1_double 1_hold , etc
LKWS211 reports button_1_single, button_1_double, button_1_hold, etc

So had to separate them in the yaml.

### CODE REVIEW

**Comment by Sian-Lee-SA** [comment]
First if you need to crop the image to the device borders, secondly if they're the same then device in theory, then use a templated condition with `or` and rename the title to include both models

**Comment by Sian-Lee-SA** [comment]
https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager?tab=readme-ov-file#template

**Comment by KipK** [comment]
I have tried to template the value: before splitting in two. 
Seeing your readme, I've also tried 
- title: press
        conditions: "{{ data.button_last_state[0].title == '1_single' or data.button_last_state[0].title == 'button_1_single' }}"

Would you mind tells me how to do it properly ? 
Thx

**Comment by Sian-Lee-SA** [comment]
something like 
```yaml
conditions: "{{ data.payload in ['1_single', 'button_1_single'] }}"
```
should suffice

**Comment by KipK** [comment]
Thanks. I've updated the PR.

**Comment by Sian-Lee-SA** [comment]
Cool, Thanks!

**Comment by Mattie432** [comment]
@Sian-Lee-SA are we able to push out a version bump to include this? Would love to test out for a `TS0042` switch.

**Comment by Sian-Lee-SA** [comment]
Why don't you just copy it to your installation? You don't need a "release" to use blueprints let alone any code changes made before a release. A release just packages things in a state.

**Comment by Mattie432** [comment]
Indeed, I was putting it in `custom_components/switch_manager/blueprints` not `config/blueprints/switch_manager`

@KipK this works great. Thanks very much for adding.

**Pull request merged**
