### PR TITLE
Trying again - Adding Moes Smart Knob

### PR DESCRIPTION
**Pull request by bleughb**
Thankyou for your patience, Still a relative noob to Github

## Blueprint Checklist

- [x] You viewed the README and conformed to the [naming conventions](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#title-naming-convention)
- [x] You ordered the actions as stated in the README [action order](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#order-convention)
- [x] All filenames are lowercase and uses '-' for spaces and **not** '_' while using {service-name}-{switch-name-or-type}.yaml format
- [x] Images are png
- [x] Image backgrounds are transparent and is cropped to the device boundries
- [x] Images has a maximum width of 800px and maximum height of 500px
- [x] There are no missing buttons or actions
- [x] Your integration/service is running on the latest version
- [x] You have tested your blueprints and made sure each button and action works

#### Zigbee2MQTT

- [ ] (**older devices**) You have ensured legacy is off/false for the device in the Z2M devices Settings (specific) page and that your actions matches those with legacy off?

### CODE REVIEW

**Comment by Sian-Lee-SA** [comment]
This PR has no changes to merge. Your previous closed PR can be updated which I can just reopen and merge. Will close this in favour of your previous PR.

**Comment by Sian-Lee-SA** [comment]
Also to be completely honest, I'm not an expert with Github myself but this PR has no changes to merge so I think there has been an issue with how or what you are wanting to push.

**Comment by Sian-Lee-SA** [comment]
After a quick investigation, it seems someone "hijacked" your PR then made their own with the same changes you made. This is why there's no changes showing for your PR because someone else did it... Sorry

**Comment by nwithan8** [comment]
Sorry about that mate, @bleughb , my bad.

**Comment by Sian-Lee-SA** [comment]
Just to be clear, the devices you make PR's for needs to be tested/owned and used previously by yourself. If so then I have no issue.

**Comment by Sian-Lee-SA** [comment]
I will merge this even though it has no changes. This then puts you under the contributers list.

**Pull request merged**
